### ISSUE TITLE
Boss recovery

### ISSUE THREAD

**Issue by PrimalPower** [Auxilor/EcoMobs#18]
I would like the new feature that a boss can recover health. 

Health per second: How much a boss naturally regenerates per second

Health on kill: How much a boss recovers if a boss kills a player

Health if hasn’t attacked: How much health a boss regenerates if it hasn’t hit a player for 20 seconds 

Health if not damaged: Health it regenerates per second if it hasn’t been damaged for 20 seconds

Percentage health on kill: The percentage of a player’s damage it recovers when it kills a player. For example, if a player has dealt 1000 damage to the boss and they die of ANY CAUSE whilst the boss is still alive and the config option is set to 50, the boss will recover 500 health and the player’s total damage will go down to 500. This will encourage survival as well as dealing the most damage. This also prevents boss griefing by repeatedly dying to the boss and healing it because it will those people would have 0 damage

**Comment by Opalinium** [comment]
+1 all the way, this would be a great feature to have!
