### ISSUE TITLE
Much needed features and fixes

### ISSUE THREAD

**Issue by mani1232** [Auxilor/EcoMobs#26]
**Is your feature request related to a problem? Please describe.**
Why does the boss stop working if no one uploads chunks with him??? (or reload plugin)

**Describe the solution you'd like**
How to make an attack for an iron golem only for the player?

And is it possible to make it so that the boss will not leave region and the player who started pvp with him too 

add support SpawnData for choose spawner, for drop, spawner skeletons or spider

Add shutdown function /fly /god and similar commands or all commands (whitelist\blacklist)

**Describe alternatives you've considered**
no

**Additional context**
no

**Comment by PrimalPower** [comment]
the first thing with the unloaded chunks is classed as a bug
