### ISSUE TITLE
Minimum damage amount to receive boss rewards/drops

### ISSUE THREAD

**Issue by KermX** [Auxilor/EcoMobs#32]
This would be a useful feature to avoid people punching a boss once and getting rewards

A way to set minimum damage in config. The same way chance is set for top damager commands, ex:
        1:
          - minimumdamage: 1000
          - chance: 100 
            commands:
              - give %player% gold_nugget 1

A way to set this more generally, just a flat minimum damage to receive rewards at all somewhere in config.

**Comment by Opalinium** [comment]
+1
