### ISSUE TITLE
Boss breaking if chunk unloads

### ISSUE THREAD

**Issue by PrimalPower** [Auxilor/EcoMobs#33]
**Describe the bug*
If the chunk an eco boss is in is unloaded  or the plugin is reloaded the boss completely breaks. It’s timer stops, bossbar stops and effects stop. 

**To Reproduce**
1. Create a boss
2. Leave spawn chunks
3. Spawn the boss
4. Teleport far far away and make sure no players within 16 chunks of the boss (assuming simulation distance < 16)
5. Wait a few minutes and teleport back
6. The boss breaks 
*Expected behavior*
The boss should still function as normal

**Screenshots**

**Server Information (please complete the following information):**
- Version: Latest Paper version
- Version of plugin and eco: Both on latest version

**Alternative fixes**
Keep chunk loaded if an eco boss is in the chunk

Despawn the boss of chunk unloaded (maybe option in config)

**Comment by DaRacci** [comment]
Should probably mark this as closed since a PR was merged to fix this

**Comment by 0ft3n** [comment]
@WillFP close, please
